#1153 - mkdir supports creation of parent directories
qorelanguage/qore pull request #1299
Opened 2016-09-29 12:55 UTC by alachata-qore

2016-09-29 13:27 UTC, davidnich requested changes
if `parents` = True then you should use `QoreDir::create()` instead of your own implementation

2016-09-29 13:27 UTC, davidnich commented on lib/ql_file.qpp
> +    @param parents if True also parrent directories are created
please fix the typo: `parrent` -> `parent`

2016-09-29 13:27 UTC, davidnich commented on lib/ql_file.qpp
> +    char sep = '\\';
this is already defined in common.h, please do not redefine - use `QORE_DIR_SEP`

2016-09-29 13:27 UTC, davidnich commented on lib/ql_file.qpp
> +    /* Copy string so its mutable */
please use c++ line comments `//`

2016-10-02 06:57 UTC, davidnich reviewed
please also add a release note `doxygen/lang/900_release_notes.dox.tmpl` - after "new function" add "updated functions" and list the changes to this function

also please add a `@since %Qore 0.8.13 added the <i>parents</i> parameter`  line to the `mkdir()` function documentation

also the return value documentation for `mkdir()` should reflect that fact that the count of newly created directories is only returned when <i>parents</i> = @ref Qore::True "True", otherwise the return value for a successful call remains `0`

2016-10-02 06:57 UTC, davidnich commented on lib/ql_file.qpp
> +    @return 0 or count of newly created directories if no error occured; -1 if an error occurred, in which case errno() and/or strerror() can be used to retrieve the error
count -> "the count" and occured -> "occurred"

2016-10-03 10:45 UTC, alachata-qore commented
Please check now.

2016-10-03 10:59 UTC, davidnich requested changes

2016-10-03 10:59 UTC, davidnich commented on doxygen/lang/900_release_notes.dox.tmpl
> +      - @ref Qore::mkdir(string path, softint mode = 0777, bool paretns = False)
please fix the typo `paretns`

2016-10-03 10:59 UTC, davidnich commented on lib/ql_file.qpp
> +    @return if no error occured returns 0 or the count of newly created directory when parents = @ref Qore::True "True"; -1 if an error occurred, in which case errno() and/or strerror() can be used t
typo - occured -> `occurred`

2016-10-03 12:44 UTC, merged