Feature/1660 SqlUtil op_in()
qorelanguage/qore pull request #1661
Opened 2017-02-10 09:10 UTC by gamato

Implements a work around for issue #1660

2017-02-10 09:15 UTC, davidnich commented on qlib/OracleSqlUtil.qm
> +                            return cn + " in (" + (map "select column_value from table(%v)", range(1,count)).join(" union all ") + ")";
please use xrange() rather than range() here: https://github.com/qorelanguage/qore/wiki/ProTips#xrange-vs-range

2017-02-10 09:17 UTC, davidnich requested changes

2017-02-10 09:17 UTC, davidnich commented on qlib/OracleSqlUtil.qm
> +    @subsection v122 OracleSqlUtil v1.2.2
please also update the module's version string in the module header to "1.2.2"

2017-02-10 09:17 UTC, davidnich commented on qlib/OracleSqlUtil.qm
> +                            return cn + " in (" + (map "select column_value from table(%v)", range(1,count)).join(" union all ") + ")";
please use `xrange()` rather than `range()` here: https://github.com/qorelanguage/qore/wiki/ProTips#xrange-vs-range

2017-02-10 09:17 UTC, davidnich commented on doxygen/lang/900_release_notes.dox.tmpl
> +      - worked around ORA-22165 from op_in() caused by Oracle's limit on number of collection elements (<a href="https://github.com/qorelanguage/qore/issues/1660">issue 1660</a>)
please put this line under the `OracleSqlUtil` module changes

2017-02-10 12:29 UTC, omusil24 commented
@gamato FreetdsSqlUtil.qtest fails because of this:
https://support.microsoft.com/en-us/help/913050/error-message-when-you-run-a-query-in-sql-server-2005-internal-error-an-expression-services-limit-has-been-reached

2017-02-11 21:28 UTC, pvanek commented
How it will work with orderby and / or aggregate functions? Also I suggest to extend docs to say that using huge in lists is a sign of potentially bad design of an application

2017-02-12 06:21 UTC, davidnich commented
@gamato as discussed, we need to first target this for 0.8.12

2017-02-12 06:37 UTC, davidnich reviewed
as discussed, we need to first target this for 0.8.12

2017-02-12 10:00 UTC, davidnich commented
@gamato @pvanek I see two issues here, of which only one is clear to me how to solve:
1) SqlUtil should make `op_in()` work with arbitrarily large argument ranges if technically possible - no problem to document that it's bad practice to use too large lists here (but we should define how large the lists should be to make them reasonable and also why)
2) how to describe to users how to make queries selecting a large number of keys/ids known at runtime and not in the database - this is not clear to me how to do it if `op_in()` is not appropriate

2017-02-14 13:06 UTC, davidnich commented
@gamato please retarget this pull request to 0.8.12 as discussed

2017-02-15 06:48 UTC, closed without merging