fixed #1688: sqlutil: oracle: character_semantics can be different fo…
qorelanguage/qore pull request #1692
Opened 2017-02-21 11:51 UTC by pvanek

…r each column, not only for the whole schema

2017-02-21 11:54 UTC, omusil24 approved these changes

2017-02-21 12:50 UTC, davidnich requested changes
please add a release note for OracleSqlUtil and increment the sub version #

2017-02-21 14:03 UTC, pvanek commented
@davidnich your requests are done

2017-02-21 14:06 UTC, davidnich approved these changes

2017-02-21 14:07 UTC, davidnich commented
added @pavelkveton as a review to approve after the 0.8.12.7 release

2017-02-22 07:54 UTC, pavelkveton approved these changes

2017-02-22 11:22 UTC, merged