Added qore_check_this back to ExceptionSink::operator bool
qorelanguage/qore pull request #1845
Opened 2017-04-25 11:42 UTC by omusil24

2017-04-25 11:44 UTC, davidnich requested changes
Let's discuss - I do not want to move backwards like this - this is invalid C++ and will cause Qore to fail to run on newer compilers

2017-04-25 11:45 UTC, pavelkveton commented
ok, let's discuss - but as written in the issue
1) this is a showstopper for releasing 0.8.12.10
2) there is >670 occurrences of `*xsink` in the code, by a quick check

2017-04-26 16:07 UTC, davidnich approved these changes

2017-04-27 04:44 UTC, davidnich commented
@pavelkveton I'm working on a cleaner and more consistent fix

2017-04-27 05:15 UTC, davidnich commented
@pavelkveton there were more long-standing bugs - even with the `qore_check_this()` workaround - long-standing potential / rare bugs where xsink could be NULL but xsink->raiseException() was called in some very rare cases - this should fix them all with a consistent approach where xsink must always be set except in one well-defined function

2017-04-27 06:26 UTC, pavelkveton commented
Hmm, I would expect that there will be additions of `xsink != NULL` so that we make the code safer.

But I see also a lot of places where this check is removed.

I take it as a cleanup in the code which is welcome but creates potential threat of null pointer dereference.

Given the code coverage we have, I could not jugde without deeper analysis of the code whether all the changes are safe.

I'd prefer simple restoring of `qore_check_this` in 0.8.12, and put these (generally welcomed) changes to 0.8.13 after thorough review.

2017-04-27 07:18 UTC, davidnich commented
@pavel ok are you ok with retargeting these changes to develop then, where we have time to find any potential issues?  or do you mean post-Qore 0.8.13?

In any case the restoration of `qore_check_this()` is not enough and some other changes will need to be made for additional bugs I found that are fixed here (ex: `qore_socket_private::bindUNIX()` with a NULL xsink)

2017-04-27 08:06 UTC, pavelkveton commented
I suggest
a) do the restoration of qore_check_this() in this fix for 0.8.12.10
b) open new issue for the problems you found with (those where "restoration of qore_check_this() is not enough"), target to 0.8.12.10
c) the code cleanup for 0.8.13

2017-04-27 09:26 UTC, davidnich commented
@pavelkveton I re-added the runtime checks for NULL xsink - please let me know if this is OK

2017-04-27 10:12 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>              return QSE_IN_OP;
why shouldn't we restore the check here?

2017-04-27 10:12 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>           return QSE_IN_OP_THREAD;
why shouldn't we check xsink here?

2017-04-27 10:13 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>                 return -1;
why the check for xsink is removed here?

2017-04-27 10:14 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>  		  qore_socket_error(xsink, "SOCKET-CONNECT-ERROR", "error in asyncIoWait() with Socket::connect() with timeout", 0, 0, 0, ai_addr);
why the check for xsink is removed here?

2017-04-27 10:14 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>  		     qore_socket_error(xsink, "SOCKET-CONNECT-ERROR", "error in getsockopt()", 0, 0, 0, ai_addr);
why the check for xsink is removed here?

2017-04-27 10:26 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>  	    break;
why the xsink check is removed here?

2017-04-27 10:26 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>  	    qore_socket_error(xsink, "SOCKET-CONNECT-ERROR", "error in connect()", 0, host, service);
why the xsink check is removed here?

2017-04-27 10:27 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
the xsink check is removed here - why?

2017-04-27 10:27 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>  		  close();
again, xsink check missing

2017-04-27 10:27 UTC, pavelkveton commented on include/qore/intern/qore_socket_private.h
>  		  qore_socket_error(xsink, "SOCKET-RECV-ERROR", "error in recv()", meth);
xsink check missing

2017-04-27 10:54 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>              return QSE_IN_OP;
the check was adde to `se_in_op()` and all error functions instead to make it easier to remove later -
```
void se_in_op(const char* cname, const char* meth, ExceptionSink* xsink) {
   assert(xsink);
   // FIXME: remove check
   if (xsink)
      xsink->raiseException("SOCKET-IN-CALLBACK", "calls to %s::%s() cannot be made from a callback on an operation on the same socket", cname, meth);
}
```

2017-04-27 10:55 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>           return QSE_IN_OP_THREAD;
same as above

2017-04-27 10:55 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>                 return -1;
because *xsink has already been fixed

2017-04-27 11:05 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>  		  qore_socket_error(xsink, "SOCKET-CONNECT-ERROR", "error in asyncIoWait() with Socket::connect() with timeout", 0, 0, 0, ai_addr);
same as above - `qore_socket_error()` has the check so it will be easier to remove later

2017-04-27 11:05 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>  		     qore_socket_error(xsink, "SOCKET-CONNECT-ERROR", "error in getsockopt()", 0, 0, 0, ai_addr);
same as above

2017-04-27 11:06 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>  	    break;
same as above

2017-04-27 11:06 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>  	    qore_socket_error(xsink, "SOCKET-CONNECT-ERROR", "error in connect()", 0, host, service);
same as above

2017-04-27 11:06 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
same as above

2017-04-27 11:07 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>  		  close();
same as above

2017-04-27 11:07 UTC, davidnich commented on include/qore/intern/qore_socket_private.h
>  		  qore_socket_error(xsink, "SOCKET-RECV-ERROR", "error in recv()", meth);
same as above

2017-04-27 11:09 UTC, davidnich commented
@omusil24 I reviewed Pavel's comments, and in all cases the changes are OK because the NULL checks (which are just for runtime safety and should not be used anymore) are localized to error methods, etc

Pavel asked me to assign to you for merging

2017-04-27 14:05 UTC, merged