Bugfix/2269 debugger fixes
qorelanguage/qore pull request #2270
Opened 2017-10-08 06:23 UTC by davidnich

changes:
- implements support for listing all local variables with `thread local`
- implements support for setting the current stack frame with `fr <id>`
- implements aliases (so `stack` is back as an alias for `bt` - along with `backtrace`)
- implements better support for partial command matches - if a partial match matches a single option, then it's used immediately (ex: `sess`, etc)
- implements optimized `pgm` and `thread` commands-
-- `pgm` => `pgm info`
-- `pgm <id>` => `pgm set <id>` 
-- `thread <id>` => `thread set <id>`

ex: with partial cmd matching: `p 310` => `pgm set 310`

@tmandys this is a usability fix to the debugger support that was added before the release

a partial list of issues to be addressed (besides issues you raised already in Qore for example):
* all server output should have custom output formatting
* better formatted default output than `%N` formatting
* evaluate frame context (server side) and thread and program context handling (client side)
* implement support for calling server-side code in the current Program context and returning the result

2017-10-08 12:00 UTC, davidnich commented
@tmandys there is now a wiki page for debugger issues here: https://github.com/qorelanguage/qore/wiki/Debugger-Implementation

2017-10-09 07:51 UTC, gamato commented
There's actually a helper function [`Util::plural()`](https://docs.qore.org/current/modules/Util/html/namespace_util.html#a04c004bc9f31c426c29f5011adc57d7a) for such use cases.

2017-10-09 09:08 UTC, omusil24 commented
One thing that I don't like is that the implementation of the command "actions" is hardcoded straight in the hash. It would be better to put it in normal functions/methods and just reference those when creating the command hash. Or at least do it like that for the bigger functions/actions.

2017-10-09 11:55 UTC, tmandys requested changes

2017-10-09 11:55 UTC, tmandys commented on qlib/DebugCmdLine.qm
> +                                    # check if the second match is the same as the first through aliases
I considered also "multi level" aliases "step" -> "go step"

2017-10-09 11:55 UTC, tmandys commented on qlib/DebugCmdLine.qm
> +                        'enum': list sub(DebugCommandLine dcl, softlist path, softlist args) {
set frame is via new level '*',  (as pgm/set/*).  This way does not work as enum is for '*' only. Also '*': 'action' should implement set-frame-functionality

2017-10-09 11:55 UTC, tmandys commented on qlib/DebugCmdLine.qm
> +                                stdout.printf("\"pgm\": takes maximum one arugment to set the current program; got %d arguments\r\n", args.size());
type "arugment" (multiple, copy paste error from my code)

2017-10-09 11:55 UTC, tmandys commented on qlib/DebugCmdLine.qm
> +                        'enum': list sub(DebugCommandLine dcl, softlist path, softlist args) {
no function, enum is for '*' only

2017-10-09 12:03 UTC, tmandys commented on qlib/DebugCmdLine.qm
> +                                },
my typo below global vs. local

2017-10-11 10:09 UTC, tmandys approved these changes

2017-10-11 10:20 UTC, merged