implemented #2314: SqlUtil: add support for custom column operators
qorelanguage/qore pull request #2315
Opened 2017-10-20 06:39 UTC by pvanek

2017-10-20 06:55 UTC, davidnich requested changes
please add a note in doxygen/lang/900_release_notes.dox.tmpl

also the SqlUtil modules should get a point update and notes

2017-10-20 06:55 UTC, davidnich commented on qlib/SqlUtil.qm
> +        /** subclasses has to implement getColumnOperatorMapImpl() to return driver-specific options
please update to `have to`

2017-10-20 07:27 UTC, pvanek commented
@davidnich relnotes added

2017-10-20 09:20 UTC, davidnich requested changes
@pvanek please update SqlUtil to v1.4.1 and move the relnote there - technically the other modules should also get version bumps and relnotes as well

2017-10-21 12:48 UTC, pvanek commented
@davidnich vesrion bump done

2017-10-21 13:34 UTC, merged