Bug/2292 debugger ambiguous matches
qorelanguage/qore pull request #2359
Opened 2017-10-30 11:17 UTC by tmandys

2017-10-30 14:55 UTC, davidnich requested changes
please add a relnote in 900_release_notes.dox.tmpl

2017-10-30 14:55 UTC, davidnich commented on qlib/DebugCmdLine.qm
> +                        if (elements keys cmd.variants > 1) {
please just use `element cmd.variants` which operates directly on the hash (returns the number of hash keys) - `elements keys variants` creates a temporary list and then returns the elements in the list - or you can use `cmd.variants.size()`

2017-10-31 02:20 UTC, omusil24 commented
Wouldn't it be good if this was in 0.8.13 too?

2017-10-31 03:04 UTC, davidnich commented
@tmandys right - this needs to be targeted against 0.8.13 - please close this and open a new one targeted to 0.8.13 (thx @omusil24)

2017-11-02 09:35 UTC, closed without merging