refs #2903 remove <run-time-loaded: label> from Program::parseXXX(), …
qorelanguage/qore pull request #2904
Opened 2018-07-18 09:02 UTC by tmandys

…format_label is obsolete

2018-07-24 05:32 UTC, davidnich requested changes

2018-07-24 05:32 UTC, davidnich commented on lib/QC_Program.qpp
> +    @param format_label obsolete since %Qore 0.8.13
needs to read `obsolete / ignored since %Qore 0.8.13.7`

2018-07-24 05:32 UTC, davidnich commented on lib/QC_Program.qpp
> +    @since %Qore 0.8.7 the \a source, \a offset, and \a format_label arguments were added. %Qore 0.8.13 the \a format_label is obsolete
`0.8.13` should read `0.8.13.7` and `obsolete` should read `obsolete / ignored`

2018-07-24 05:32 UTC, davidnich commented on lib/QC_Program.qpp
> +    @param format_label obsolete since %Qore 0.8.13
as above

2018-07-24 05:32 UTC, davidnich commented on lib/QC_Program.qpp
> +    @since %Qore 0.8.7 the \a source, \a offset, and \a format_label arguments were added. %Qore 0.8.13 the \a format_label is obsolete
as above

2018-07-24 05:32 UTC, davidnich commented on lib/ql_misc.qpp
> +    @param format_label %Qore 0.8.13 is obsolete
as above

2018-07-24 05:32 UTC, davidnich commented on lib/ql_misc.qpp
> +    @since %Qore 0.8.7 the optional \a warning_mask, \a source, \a offset, and \a format_label arguments were added; %Qore 0.8.13 the \a format_label is obsolete;
as above

2018-07-25 14:26 UTC, tmandys commented
Docs fixed

2018-08-23 09:44 UTC, closed without merging