Bugfix/2932 swagger fix
qorelanguage/qore pull request #2935
Opened 2018-08-08 13:59 UTC by petrytar

2018-08-08 14:01 UTC, davidnich requested changes
please add a line in `Swagger.qm` in the `@section swagger_relnotes Swagger Module Release Note` section for the new release + the change, and then it's fine for me.  Please assign to @sejvlond for merging after that

2018-08-08 14:41 UTC, petrytar commented
done

2018-08-08 18:16 UTC, davidnich approved these changes

2018-08-09 00:52 UTC, omusil24 approved these changes

2018-08-09 06:09 UTC, merged