Feature/2905 debug source code by label
qorelanguage/qore pull request #2945
Opened 2018-08-15 13:42 UTC by tmandys

2018-08-15 13:52 UTC, davidnich requested changes

2018-08-15 13:52 UTC, davidnich commented on doxygen/lang/900_release_notes.dox.tmpl
> +        - @ref DebugHandler reimplemented to support multiple websocket handlers
`@ref DebugHandler` will not work; you have to use `<a href="../../modules/DebugHandler/html/index.html">DebugHandler</a>` instead.  Please always generate the documentation and review the output before submitting a pull request

2018-08-15 13:52 UTC, davidnich commented on examples/test/qore/debug/test-debug.qtest
>        'func': stResolve{func},
does this file have 2-space indentation?  it should be 4

2018-08-15 13:52 UTC, davidnich commented on examples/test/qore/debug/test-debug.qtest
>      any act = getAction(func);
please use `auto` instead of `any` as `any` is subject to type stripping (performance issue)

2018-08-15 19:47 UTC, tmandys commented
requested changes from review done

2018-08-19 05:08 UTC, davidnich commented
@tmandys as per my email this weekend, I would like to retarget this and all other enhancements to libqore to develop, let's discuss if you have any objections

2018-08-22 22:05 UTC, closed without merging